version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=Elastic@123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  enterprise-search:
    image: docker.elastic.co/enterprise-search/enterprise-search:8.18.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - ENT_SEARCH_DEFAULT_PASSWORD=Elastic@123
      - elasticsearch.username=elastic
      - elasticsearch.password=Elastic@123
      - elasticsearch.host=http://elasticsearch:9200
      - allow_es_settings_modification=true
      - secret_management.encryption_keys=["4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09"]
      - elasticsearch.startup_retry.interval=15
    ports:
      - "3002:3002"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=<fill in username>
      - ELASTICSEARCH_PASSWORD=<fill in password>
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  elasticsearch-data:

networks:
  elastic:
    driver: bridge

